11th add  echo if error and error if failed

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -61,7 +61,7 @@ jobs:
             --query 'Command.CommandId' \
             --output text)
 
-            echo "Command ID: $command_id"
+            # echo "Command ID: $command_id"
 
             aws ssm wait command-executed \
             --command-id $command_id \
@@ -79,9 +79,11 @@ jobs:
 
             echo "$status"
 
-            if [ "$status" == "Success" ]; then
+            if [ $status == "Success" ]; then
               echo "Command executed successfully"
             else 
               echo "Command failed"
+              echo "Error: "$status"
+              exit 1
             fi
           
