correct

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -70,7 +70,7 @@ jobs:
               "echo Pulling Docker image",
               "docker pull ${{ steps.login-aws-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}",
               "echo Running Docker container",
-              "docker run -d -p 3000:3000 --name api ${{ steps.login-aws-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}"
+              "docker run -d -p 3000:3000 -e ENVIRONMENT=production --name api ${{ steps.login-aws-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}"
               ]' \
             --query 'Command.CommandId' \
             --output text)
@@ -81,22 +81,21 @@ jobs:
             aws ssm wait command-executed \
             --command-id $command_id \
             --instance-id ${{secrets.INSTANCE_ID_2}} || true 
-            for instance_id in i-079b8a960de1eb7e7 i-03e076b90fc93fcb1; do
-              status=$(aws ssm list-command-invocations \
-              --command-id $command_id \
-              --instance-id $instance_id \
-              --query "CommandInvocations[0].Status" \
-              --output text)
-              echo "Instance $instance_id status: $status"
-              if [ "$status" != "Success" ]; then
-                echo "Fetching command invocation details for instance $instance_id"
-                aws ssm list-command-invocations \
-                  --command-id $command_id \
-                  --instance-id $instance_id \
-                  --details \
-                  --output json | jq -r '.CommandInvocations[0].CommandPlugins[].Output'
-                echo "Command failed on instance $instance_id"
-                exit 1
-              fi
+            status=$(aws ssm list-command-invocations \
+            --command-id $command_id \
+            --instance-id $instance_id \
+            --query "CommandInvocations[0].Status" \
+            --output text)
+            echo "Instance $instance_id status: $status"
+            if [ "$status" != "Success" ]; then
+              echo "Fetching command invocation details for instance $instance_id"
+              aws ssm list-command-invocations \
+                --command-id $command_id \
+                --instance-id $instance_id \
+                --details \
+                --output json | jq -r '.CommandInvocations[0].CommandPlugins[].Output'
+              echo "Command failed on instance $instance_id"
+              exit 1
+            fi
             done
             echo "Command executed successfully on all instances"
